name: weatherapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  http: ^1.6.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.14.0
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  equatable: ^2.0.3
  intl: ^0.17.0
  location: ^8.0.1
  google_maps_flutter_ios: ^2.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - .env
